### ISSUE TITLE
Released version does not seem compatible with recent ktor

### ISSUE THREAD

**Issue by peterbecker** [zensum/ktor-health-check#2]
I tried using the only released version on JitPack: `implementation("com.github.zensum:ktor-health-check:legacy-ktor")`, but that seems to fail with ktor 1.1.2 -- but that fails with this in the Gradle build:

```
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version.
```

IntelliJ seems slightly more happy, but complains about the `install(Health)` part with a type mismatch (expected `ApplicationFeature<Application, ???, ???>`, found `Health.Feature`).

I suspect the "legacy" in the tag is a giveaway, but I can't see another release. Will I have to build it myself?

Cheers,
   Peter

**Comment by pn** [comment]
Try using latest version like this:
`implementation("com.github.zensum:ktor-health-check:011a5a8")`

**Comment by pn** [comment]
Made a release to bump version on the tag which should clear confusion which version to use.

**Comment by peterbecker** [comment]
Cheers - looks good. I didn't realize I could reference by hash.

**Comment by pn** [comment]
You can always check Builds or Commits tabs on jitpack.io to see other available builds to use if they are not officially released.
